version: 0.2

env:
  variables:
    S3_BUCKET: "MY_BUCKET"
    REGION: "us-east-1"
    INSTANCE_TAG_VALUE: "myapp-server"   # tag value used on EC2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Install phase"
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Pre-build: show env"
      - python --version
      - echo "Commit: $CODEBUILD_RESOLVED_SOURCE_VERSION"
  build:
    commands:
      - echo "Building artifact..."
      - zip -r app_${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip .
      - ls -la
  post_build:
    commands:
      - echo "Uploading artifact to s3..."
      - aws s3 cp app_${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip s3://$S3_BUCKET/builds/app_${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip --region $REGION
      - echo "Invoke SSM to deploy on EC2 instances with tag Name=$INSTANCE_TAG_VALUE"
      - |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=$INSTANCE_TAG_VALUE" \
          --parameters commands=["/usr/bin/aws s3 cp s3://$S3_BUCKET/builds/app_${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip /tmp/app.zip --region $REGION","unzip -o /tmp/app.zip -d /home/ec2-user/myapp","/usr/bin/pip3 install -r /home/ec2-user/myapp/requirements.txt","/bin/sudo /bin/systemctl restart myapp.service"] \
          --comment "Deploy commit $CODEBUILD_RESOLVED_SOURCE_VERSION" \
          --region $REGION
artifacts:
  files:
    - app_${CODEBUILD_RESOLVED_SOURCE_VERSION}.zip