version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10   # or match your Ubuntu EC2 python version
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli

  build:
    commands:
      - echo "Zipping app source code..."
      - zip -r app.zip ./*

  post_build:
    commands:
      - echo "Copying artifact to S3..."
      - aws s3 cp app.zip s3://ci-cd-demo-cokang/build-output.zip
      - echo "Triggering remote deployment via SSM..."
      - aws ssm send-command \
          --targets "Key=instanceIds,Values=i-0d313aa7e447ab844" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Flask App" \
          --parameters 'commands=[
            "aws s3 cp s3://ci-cd-demo-cokang/build-output.zip /tmp/build-output.zip",
            "mkdir -p /home/ubuntu/myapp",
            "unzip -o /tmp/build-output.zip -d /home/ubuntu/myapp",
            "unzip -o /home/ubuntu/myapp/app.zip -d /home/ubuntu/myapp",
            "/usr/bin/pip3 install -r /home/ubuntu/myapp/requirements.txt",
            "sudo systemctl restart myapp.service"
          ]'
artifacts:
  files:
    - app.zip