version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build completed. Running tests..."
      - python -m py_compile app.py   # simple syntax check
      - zip -r app.zip . -x "*.git*"
artifacts:
  files:
    - app.zip
